Repository ExpTechTW/trem-analyze-web, pull requests merged in 2025-03, with the labels that each got.

#2 feat: cwa info
  .github/workflows/pr.yml
  bun.lock
  eslint.config.mjs
  package.json
  src/app/info/page.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/components/earthquake-data-table.tsx
  src/components/earthquake-info-table.tsx
  src/components/enhanced-pagination.tsx
  src/components/ui/button.tsx
  src/components/ui/checkbox.tsx
  src/components/ui/input.tsx
  src/components/ui/pagination.tsx
  src/components/ui/progress.tsx
  src/components/ui/select.tsx
  src/components/ui/table.tsx
  src/hooks/useDarkMode.ts
  src/lib/utils.ts
  src/modal/earthquake.ts
  src/modal/region.ts
  src/modal/station.ts
Labels: size/XXL

#4 fix: workflow
  .github/workflows/build.yml
  .github/workflows/pr.yml
Labels: size/XS

#5 fix: info table
  .github/workflows/build.yml
  src/components/earthquake-info-table.tsx
Labels: size/XS

#6 fix: info table
  src/components/earthquake-info-table.tsx
Labels: size/S

#7 fix data table
  src/components/earthquake-data-table.tsx
Labels: size/S

#8 Refactor data page
  bun.lock
  bun.lockb
  package.json
  src/components/earthquake-data-table.tsx
  src/components/earthquake-info-table.tsx
  src/components/ui/dialog.tsx
  src/components/warn-dialog.tsx
Labels: size/L
